### ISSUE TITLE
Could someone explain what the purpose of this is?

### ISSUE THREAD

**Issue by github-account1111** [UraniumDonut/nbfc-revive#48]
**Is your feature request related to a problem? Please describe.**
Apologies if this is the wrong template.
This is a sincere question. As far as I can tell, my laptop already ramps up the fans when needed and stays quiet when not, just like every other laptop I've tried, save for the passively cooled ones. Even without the "gaming software" it came with.

**Describe the solution you'd like**

**Additional context**

**Comment by satcom886** [comment]
You may have been lucky. Two of my laptops have a very passive curve that never reaches 100%. Using NBFC, I can change the fan curve to get there when it's needed. Doing so allows some extra turbo headroom at the cost of the added noise.

One laptop I have on the other hand has a very aggressive curve and it's very annoying to use just because of that.

Simply put, NBFC gives you the freedom to change the fan curve if you know you need it. Not everyone needs/wants that and that's fine.

**Comment by UraniumDonut** [comment]
@satcom886 is correct
